baseURL: https://churchintouraine.org
languageCode: "en-GB"
title: Touraine and the church of St Alcuin
theme: ghostwriter

pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

taxonomies:
  tag: tags



params:
  mainSections:
    - post
  intro: true
  headline: Touraine and the church of St Alcuin
  description: "Touraine and the church of St Alcuin"
  author: Touraine and the church of St Alcuin
  email: 
  rss: true
  shareFacebook: true
  dateFormat: "Mon, 2 Jan, 2006"
  readingTime: true
  readingTimeText: "Estimated reading time:"

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Pages
      url: /Page/
      weight: 2

#module:
#  imports:
#  - path: github.com/jbub/ghostwriter

